name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Create file
        run: cat /home/runner/work/ikpmd_jetpack_compose/ikpmd_jetpack_compose/app/google-services.json | base64
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/ikpmd_jetpack_compose/ikpmd_jetpack_compose/app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build
